apiVersion: v1
kind: Service
metadata:
  name: {{ include "ha-cluster.fullname" . }}
  labels:
    {{ include "ha-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "ha-cluster.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ha-cluster.fullname" . }}-headless
  labels:
    {{ include "ha-cluster.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  clusterIP: None
  selector:
    app: {{ include "ha-cluster.name" . }}