vault:
  image:
    repository: vault
    tag: 1.10.3
  ha:
    enabled: true
    nodes: 3
  config:
    storage:
      backend: azure
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: 1
    seal:
      wrap_ttl: 10m
      max_ttl: 30m
    cluster_name: "vault-cluster"


# Azure configuration
azure:
  subscription_id: <your_subscription_id>
  tenant_id: <your_tenant_id>
  client_id: <your_client_id>
  client_secret: <your_client_secret>
  resource_group: <your_resource_group>
  storage_account: <your_storage_account>

# Kubernetes configuration
kubernetes:
  namespace: vault
  service_account: vault