apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.hcl: |
    storage "azure" {
      subscription_id = "{{ .Values.azure.subscription_id }}"
      tenant_id = "{{ .Values.azure.tenant_id }}"
      client_id = "{{ .Values.azure.client_id }}"
      client_secret = "{{ .Values.azure.client_secret }}"
      resource_group = "{{ .Values.azure.resource_group }}"
      storage_account = "{{ .Values.azure.storage_account }}"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    seal "azurekeyvault" {
      wrap_ttl = "10m"
      max_ttl = "30m"
    }
    cluster_name = "{{ .Values.vault.config.cluster_name }}"