apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: {{ .Values.vault.ha.nodes }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: {{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}
        args:
        - server
        - -config=/vault/config/vault.hcl
        - -log-level=debug
        volumeMounts:
        - name: config
          mountPath: /vault/config
        - name: storage
          mountPath: /vault/data
      volumes:
      - name: config
        configMap:
          name: vault-config
      - name: storage
        persistentVolumeClaim:
          claimName: vault-storage